version: '3.8'

services:
  db:
    image: postgres:15
    container_name: shipflow_db
    restart: always
    environment:
      POSTGRES_DB: shipflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jkanime123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: shipflow_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shipflow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Jkanime123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  pgdata: